### ISSUE TITLE
Open source repo setup

### ISSUE THREAD

**Issue by jakebolam** [tophatmonocle/yvm#2]
- [x] Create repo
- [x] Collaborators
- [x] CircleCI (Test runner, auto publish to install script in the future)
- [x] Basic PR template
- [x] Basic issue template #94 
- [x] Basic Readme
- [ ] Basic Contributing
- [ ] Open source license

**Comment by umar-tophat** [comment]
https://github.com/tophatmonocle/yvm/community

**Comment by jakebolam** [comment]
See #93 and #94.

Will add license later
