### ISSUE TITLE
Installing an invalid version fails

### ISSUE THREAD

**Issue by nepodmitljivi** [tophatmonocle/yvm#20]
```milan:yvm` milanmilojic$ npm start install 1.0.2

> @thm/yvm@1.0.0 start /Users/milanmilojic/dev/yvm
> node yvm.js "install" "1.0.2"

Installing yarn v1.0.2
Finished downloading yarn version 1.0.2
Finished extracting yarn version 1.0.2
milan:yvm milanmilojic$ npm start install 1.0.3

> @thm/yvm@1.0.0 start /Users/milanmilojic/dev/yvm
> node yvm.js "install" "1.0.3"

Installing yarn v1.0.3
Finished downloading yarn version 1.0.3
{ Error: incorrect header check
    at Zlib._handle.onerror (zlib.js:371:17) errno: -3, code: 'Z_DATA_ERROR' }
milan:yvm milanmilojic$```
leaves us with with invalid tarball
```milan:versions milanmilojic$ ls -lna
total 256
drwxr-xr-x  5 501  20     160 Jun 18 17:04 .
drwxr-xr-x  3 501  20      96 Jun 18 16:15 ..
drwxr-xr-x  7 501  20     224 Jun 18 17:04 v1.0.2
-rw-r--r--  1 501  20  129195 Jun 18 17:04 v1.0.3.tar.gz
drwxr-xr-x  7 501  20     224 Jun 18 17:01 v1.7.0```

**Comment by brandonbaksh** [comment]
Our current way of installing yarn will not work for versions under 1.0.0 due to the fact that there is no top level folder in the archive
