### ISSUE TITLE
Make sure that user has minimum node version

### ISSUE THREAD

**Issue by brandonbaksh** [tophatmonocle/yvm#31]
Currently yvm is built on node 8.11.3. If a user tries to use yvm with a lower version (e.g 6.11.5) it will throw a syntax error. 

This can be tackled by either: 
1. Displaying a message to ensure the correct node version (index.js)
2. Using backwards compatible syntax

**Comment by umar-tophat** [comment]
This has been fixed by using Babel to transpile to at least Node 4 syntax in #48
