### ISSUE TITLE
Support install on shells other than zsh

### ISSUE THREAD

**Issue by jakebolam** [tophatmonocle/yvm#44]

**Comment by umar-tophat** [comment]
`yvm use` requires sourcing the yvm path in `.bashrc` or `.bash_profile`.

**Comment by umar-tophat** [comment]
As @brandonbaksh noted, we still need to add `YVM_DIR` to `.bash_profile`.

**Comment by francoiscampbell** [comment]
this is getting stale, let's track each shell individually, starting with #116
